-- This file migrates a database from the monolothic
-- music publisher database for use with the modularized
-- mpdb system

alter table tx_publisherdb_domain_model_form rename to tx_dmnorm_domain_model_gndgenre;
alter table tx_publisherdb_domain_model_instrument rename to tx_dmnorm_domain_model_gndinstrument;
alter table tx_publisherdb_domain_model_mvdbgenre rename to tx_dmont_domain_model_genre;
alter table tx_publisherdb_domain_model_mvdbinstrument rename to tx_dmont_domain_model_instrument;
alter table tx_publisherdb_domain_model_mvdbinstrumentation rename to tx_dmont_domain_model_mediumofperformance;
alter table tx_publisherdb_domain_model_person rename to tx_dmnorm_domain_model_gndperson;
alter table tx_publisherdb_domain_model_place rename to tx_dmnorm_domain_model_gndplace;
alter table tx_publisherdb_domain_model_publisher rename to tx_mpdbcore_domain_model_publisher;
alter table tx_publisherdb_domain_model_publishermakroitem rename to tx_mpdbcore_domain_model_publisheditem;
alter table tx_publisherdb_domain_model_publishermikroitem rename to tx_mpdbcore_domain_model_publishedsubitem;
alter table tx_publisherdb_domain_model_work rename to tx_dmnorm_domain_model_gndwork;
alter table tx_publisherdb_form_form_mm rename to tx_dmnorm_gndgenre_gndgenre_mm;
alter table tx_publisherdb_instrument_instrument_mm rename to tx_dmnorm_gndinstrument_gndinstrument_mm;
alter table tx_publisherdb_mvdbinstrumentation_mvdbinstrument_mm rename to tx_dmont_mediumofperformance_instrument_mm;
alter table tx_publisherdb_person_placeofactivity_place_mm rename to tx_dmnorm_gndperson_placeofactivity_place_mm;
alter table tx_publisherdb_publishermakroitem_firstcomposer_person_mm rename to tx_mpdbcore_publisheditem_firstcomposer_person_mm;
alter table tx_publisherdb_publishermakroitem_instrument_mm rename to tx_mpdbcore_publisheditem_instrument_mm;
alter table tx_publisherdb_publishermakroitem_person_mm rename to tx_mpdbcore_publisheditem_person_mm;
alter table tx_publisherdb_publishermakroitem_work_mm rename to tx_mpdbcore_publisheditem_work_mm;
alter table tx_publisherdb_publishermikroitem_work_mm rename to tx_mpdbcore_publishedsubitem_work_mm;
alter table tx_publisherdb_work_altinstrumentation_mvdbinstrumentation_mm rename to tx_dmont_work_altmediumofperformance_mediumofperformance_mm;
alter table tx_publisherdb_work_form_mm rename to tx_dmnorm_gndwork_gndgenre_mm;
alter table tx_publisherdb_work_instrument_mm rename to tx_dmnorm_gndwork_gndinstrument_mm;
alter table tx_publisherdb_work_mvdbgenre_mm rename to tx_dmont_work_genre_mm;
alter table tx_mpdbcore_domain_model_publishedsubitem CHANGE `publisher_makro_item` `publisheditem` INT(10) UNSIGNED NOT NULL DEFAULT '0';
alter table tx_mpdbcore_domain_model_publisheditem CHANGE `publisher_mikro_item` `published_subitem` INT(10) UNSIGNED NOT NULL DEFAULT '0';
alter table tx_dmnorm_domain_model_gndgenre CHANGE `super_form` `super_gnd_genre` INT(10) UNSIGNED NOT NULL DEFAULT '0';
